---
- name: Install basic tools
  package:
    state: present
    name:
    - "vim"
    - "base-devel"
    - "time"
    - "python2"
    - "htop"
    - "subversion"
    - "asciidoc"
    - "bash"
    - "bc"
    - "binutils"
    - "bzip2"
    - "fastjar"
    - "flex"
    - "git"
    - "gcc" 
    - "util-linux"
    - "gawk"
    - "intltool"
    - "zlib"
    - "make"
    - "cdrkit"
    - "ncurses"
    - "openssl"
    - "patch"
    - "perl-extutils-makemaker"
    - "rsync"
    - "unzip"
    - "wget"
    - "gettext"
    - "libxslt"
    - "boost"
    - "libusb"
    - "bin86"
    - "sharutils"
    - "b43-fwcutter"
    - "findutils"
    - "gperf"
    - "gperftools"
    - "python"
    - "python-pip"
    - "python-setuptools"
    - "python-cryptography"
    - "help2man"
    - "dnsutils"
    - "net-tools"
    - "ansible"
    - "ansible-lint"

- name: Create a symlink to home directory
  file:
    state: link
    src: "/vagrant_home/"
    dest: "/home/jiri/home"
