---
- name: Create the github file
  copy:
    content: |
      user: {{ github_user }}
      token: {{ github_token }}
    owner: jiri
    group: jiri
    dest: /home/jiri/github_token

- name: Set global git email
  git_config:
    name: user.email
    value: "{{ git_email }}"
    scope: system

- name: Set global git name
  git_config:
    name: user.name
    value: "{{ git_name }}"
    scope: system

