---
- name: Check if package-query is installed
  command: pacman -Qi yaourt
  register: package_query_check
  changed_when: package_query_check.rc == 1
  failed_when: package_query_check.rc not in [0,1]

- name: Check if yaourt is installed
  command: pacman -Qi yaourt
  register: yaourt_check
  changed_when: yaourt_check.rc == 1
  failed_when: yaourt_check.rc not in [0,1]

- name: Download package-query
  command: git clone https://aur.archlinux.org/package-query.git
  when: package_query_check.rc != 0

- name: Install package-query
  command: makepkg -si --noconfirm
  args:
    chdir: package-query
  become_user: vagrant
  when: package_query_check.rc != 0

- name: Remove previous yaourt directories
  file:
    state: absent
    path: package-query
  when: package_query_check.rc != 0

- name: Download yaourt
  command: git clone https://aur.archlinux.org/yaourt.git
  when: yaourt_check.rc != 0

- name: Install yaourt
  command: makepkg -si --noconfirm
  args:
    chdir: yaourt
  become_user: vagrant
  when: yaourt_check.rc != 0

- name: Remove previous yaourt directories
  file:
    state: absent
    path: yaourt
  when: yaourt_check.rc != 0

